# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.pre.zsh"
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


# zmodload zsh/zprof
# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export POSTGRESQL_HOME=~/PostgreSQL/pg11/bin
export GPG_TTY=$(tty)
export ANDROID_HOME=$HOME/Library/Android/sdk
export GOPATH=/Users/tomokokawase/go
export FLUTTER_INSTALL_PATH=~/flutter
export RUST_SRC_PATH=~/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library
export PATH=$PATH:$FLUTTER_INSTALL_PATH/flutter/bin
export PATH=$PATH:~/tmux
export PATH=$PATH:/usr/local/opt/python@3.9/bin
export PATH=$PATH:/usr/local/bin
export PATH=$PATH:~/Downloads/doas-for-mac
export PATH=$PATH:/bin:/usr/bin
export PATH=$PATH:/usr/bin/strip
export PATH=$PATH:$RUST_SRC_PATH
export PATH=$PATH:~/wabt/bin
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:~/emsdk
export PATH=$PATH:~/emsdk/node/12.9.1_64bit/bin
export PATH=$PATH:~/emsdk/upstream/emscripten
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:/Applications/apache-tomcat-8.5.39/bin
export PATH=$PATH:~/go/bin:$PATH
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:/usr/local/mysql/bin
export PATH=$PATH:$POSTGRESQL_HOME
export PATH=$PATH:$HOME/.cargo/bin
export PATH=$PATH:/usr/local/lib/node_modules/bin
export PATH=$PATH:~/Desktop/protobuf-3.9.1
export PATH=$PATH:/Applications/Racket\ v8.7/bin

# Path to your oh-my-zsh installation.
export ZSH="/Users/tomokokawase/.oh-my-zsh"
export NODE_OPTIONS="--max-old-space-size=4096"
# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="ys"

alias alacritty-colorscheme="/Users/tomokokawase/Library/Python/3.7/bin/alacritty-colorscheme"
alias ys="yarn start"
alias yb="yarn build"
alias ls="exa"
alias nv="nvim"
alias jest="/usr/local/bin/jest"

export PATH="/usr/local/opt/binutils/bin:$PATH"
alias  strip="/usr/bin/strip"


### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node \
    zdharma-continuum/zinit-annex-patch-dl \
    zdharma-continuum/zinit-annex-rust

### End of Zinit's installer chunk

zinit light romkatv/zsh-defer.git
zinit ice lucid wait='1'
zinit light skywind3000/z.lua
zinit ice lucid wait='0' atinit='zpcompinit'
zinit light zdharma/fast-syntax-highlighting
zinit ice lucid wait="0" atload='_zsh_autosuggest_start'
zinit light zsh-users/zsh-autosuggestions
zinit ice lucid wait='0'
zinit light zsh-users/zsh-completions
zinit ice depth=1; 
zinit light romkatv/powerlevel10k

zinit ice lucid wait='1'
zsh-defer source ~/.nvm/nvm.sh --no-use

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


# Setting for the new UTF-8 terminal support in Lion
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

alias k='kinit --keychain zhanghaoyang.tomoko@BYTEDANCE.COM'

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"

[ -f "/Users/tomokokawase/.ghcup/env" ] && source "/Users/tomokokawase/.ghcup/env" # ghcup-env

# pnpm
export PNPM_HOME="/Users/tomokokawase/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
export OPENAI_API_KEY="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"
# pnpm end
