colors:
  # Default colors
  primary:
    background: '0x0d1117'
    foreground: '0xb3b1ad'

  # Normal colors
  normal:
    black: '0x484f58'
    red: '0xff7b72'
    green: '0x3fb950'
    yellow: '0xd29922'
    blue: '0x58a6ff'
    magenta: '0xbc8cff'
    cyan: '0x39c5cf'
    white: '0xb3b1ad'

  # Bright colors
  bright:
    black: '0x6e7681'
    red: '0xffa198'
    green: '0x56d364'
    yellow: '0xe3b341'
    blue: '0x79c0ff'
    magenta: '0xd2a8ff'
    cyan: '0x39c5cf'
    white: '0xb3b1ad'

  indexed_colors:
    - { index: 16, color: '0xd18616' }
    - { index: 17, color: '0xffa198' }
# colors:
#   name: vscode (dark)
#   author: senpai-10
#   primary:
#     background: "#1E1E1E"
#     foreground: "#D4D4D4"
#   cursor:
#     text: "#1d1f21"
#     cursor: "#cccccc"
#   normal:
#     black: "#000000"
#     red: "#cd3131"
#     green: "#0dbc79"
#     yellow: "#e5e510"
#     blue: "#2472c8"
#     magenta: "#bc3fbc"
#     cyan: "#11a8cd"
#     white: "#e5e5e5"
#   bright:
#     black: "#666666"
#     red: "#f14c4c"
#     green: "#23d18b"
#     yellow: "#f5f543"
#     blue: "#3b8eea"
#     magenta: "#d670d6"
#     cyan: "#29b8db"
#     white: "#e5e5e5"
# theme: vscode.dark
key_bindings:
  - { key: A, mods: Alt, chars: "\ea" }
  - { key: B, mods: Alt, chars: "\eb" }
  - { key: C, mods: Alt, chars: "\ec" }
  - { key: D, mods: Alt, chars: "\ed" }
  - { key: E, mods: Alt, chars: "\ee" }
  - { key: F, mods: Alt, chars: "\ef" }
  - { key: G, mods: Alt, chars: "\eg" }
  - { key: H, mods: Alt, chars: "\eh" }
  - { key: I, mods: Alt, chars: "\ei" }
  - { key: J, mods: Alt, chars: "\ej" }
  - { key: K, mods: Alt, chars: "\ek" }
  - { key: L, mods: Alt, chars: "\el" }
  - { key: M, mods: Alt, chars: "\em" }
  - { key: N, mods: Alt, chars: "\en" }
  - { key: O, mods: Alt, chars: "\eo" }
  - { key: P, mods: Alt, chars: "\ep" }
  - { key: Q, mods: Alt, chars: "\eq" }
  - { key: R, mods: Alt, chars: "\er" }
  - { key: S, mods: Alt, chars: "\es" }
  - { key: T, mods: Alt, chars: "\et" }
  - { key: U, mods: Alt, chars: "\eu" }
  - { key: V, mods: Alt, chars: "\ev" }
  - { key: W, mods: Alt, chars: "\ew" }
  - { key: X, mods: Alt, chars: "\ex" }
  - { key: Y, mods: Alt, chars: "\ey" }
  - { key: Z, mods: Alt, chars: "\ez" }
  - { key: A, mods: Alt|Shift, chars: "\eA" }
  - { key: B, mods: Alt|Shift, chars: "\eB" }
  - { key: C, mods: Alt|Shift, chars: "\eC" }
  - { key: D, mods: Alt|Shift, chars: "\eD" }
  - { key: E, mods: Alt|Shift, chars: "\eE" }
  - { key: F, mods: Alt|Shift, chars: "\eF" }
  - { key: G, mods: Alt|Shift, chars: "\eG" }
  # - { key: H, mods: Alt|Shift, chars: "\eH" }
  - { key: I, mods: Alt|Shift, chars: "\eI" }
  - { key: J, mods: Alt|Shift, chars: "\eJ" }
  - { key: K, mods: Alt|Shift, chars: "\eK" }
  - { key: L, mods: Alt|Shift, chars: "\eL" }
  - { key: M, mods: Alt|Shift, chars: "\eM" }
  - { key: N, mods: Alt|Shift, chars: "\eN" }
  - { key: O, mods: Alt|Shift, chars: "\eO" }
  - { key: P, mods: Alt|Shift, chars: "\eP" }
  - { key: Q, mods: Alt|Shift, chars: "\eQ" }
  - { key: R, mods: Alt|Shift, chars: "\eR" }
  - { key: S, mods: Alt|Shift, chars: "\eS" }
  - { key: T, mods: Alt|Shift, chars: "\eT" }
  - { key: U, mods: Alt|Shift, chars: "\eU" }
  - { key: V, mods: Alt|Shift, chars: "\eV" }
  - { key: W, mods: Alt|Shift, chars: "\eW" }
  - { key: X, mods: Alt|Shift, chars: "\eX" }
  - { key: Y, mods: Alt|Shift, chars: "\eY" }
  - { key: Z, mods: Alt|Shift, chars: "\eZ" }
  - { key: Key1, mods: Alt, chars: "\e1" }
  - { key: Key2, mods: Alt, chars: "\e2" }
  - { key: Key3, mods: Alt, chars: "\e3" }
  - { key: Key4, mods: Alt, chars: "\e4" }
  - { key: Key5, mods: Alt, chars: "\e5" }
  - { key: Key6, mods: Alt, chars: "\e6" }
  - { key: Key7, mods: Alt, chars: "\e7" }
  - { key: Key8, mods: Alt, chars: "\e8" }
  - { key: Key9, mods: Alt, chars: "\e9" }
  - { key: Key0, mods: Alt, chars: "\e0" }
  - { key: Space, mods: Control, chars: "\0" }
  # Ctrl + Space
  - { key: Grave, mods: Alt, chars: "\e`" }
  # Alt + `
  - { key: Grave, mods: Alt|Shift, chars: "\e~" }
  # Alt + ~
  - { key: Period, mods: Alt, chars: "\e." }
  # Alt + .
  - { key: Comma, mods: Alt, chars: "\e," }
  # Alt + <
  - { key: Key8, mods: Alt|Shift, chars: "\e*" }
  # Alt + *
  - { key: Key3, mods: Alt|Shift, chars: "\e#" }
  # Alt + #
  - { key: Period, mods: Alt|Shift, chars: "\e>" }
  # Alt + >
  - { key: Comma, mods: Alt|Shift, chars: "\e<" }
  # Alt + <
  - { key: Minus, mods: Alt|Shift, chars: "\e_" }
  # Alt + _
  - { key: Key5, mods: Alt|Shift, chars: "\e%" }
  # Alt + %
  - { key: Key6, mods: Alt|Shift, chars: "\e^" }
  # Alt + ^
  - { key: Backslash, mods: Alt, chars: "\e\\" }
  # Alt + \
  - { key: Backslash, mods: Alt|Shift, chars: "\e|" }
  # Alt + |
  - { key: Q, mods: Command, action: None }
  - { key: W, mods: Command, action: None }
  - { key: Back, action: ReceiveChar }
font:
  normal:
    family: "JetbrainsMonoNL Nerd Font"
    style: ExtraLight
    # family: "CaskaydiaCove Nerd Font Mono"
    # style: Regular 
  bold:
    family: "JetbrainsMonoNL Nerd Font"
    # style: Regular
    style: SemiBold
    # family: "CaskaydiaCove Nerd Font Mono"
    # style: SemiBold
  italic:
    # family: "CaskaydiaCove Nerd Font Mono"
    # style: ExtraLight Italic
    family: "JetbrainsMonoNL Nerd Font"
    style: ExtraLight Italic
  bold_italic:
    # family: "CaskaydiaCove Nerd Font Mono"
    # style: SemiBold Italic
    family: "JetbrainsMonoNL Nerd Font"
    # style: Regular Italic
    style: SemiBold Italic
  # 字大小
  size: 13
  # use_thin_strokes: true

  offset:
    x: 1
    y: 2
  glyph_offset:
    x: 0
    y: 0

window:
  padding:
    x: 2
    y: 0
  decorations: "buttonless"
  # opacity: 0.95
  # opacity: 0.85
  opacity: 0.90
  # opacity: 1
  dynamic_padding: true

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true
theme: github_dark_default
